version: '3'
services:
  redis:
    image: redis
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: gym-tracker
    ports:
      - '5432:5432'
  server:
    image: server
    ports:
      - '4000:4000'
    depends_on:
      - redis
      - db
  web:
    image: web
    ports:
      - '3000:3000'
